version: "2.2"

services:
  node_app:
    container_name: node_app
    restart: always
    depends_on:
      - node_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  node_db:
    container_name: node_mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test_db
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  db_data:
